/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Log;

import Interfaz.Cajero;
import Interfaz.Gerente;
import Interfaz.Mesero;
import JPAControl.EmpleadoJpaController;
import JPAControl.PedidoJpaController;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import restaurantetorteli.Empleado;

/**
 *
 * @author Alejandro
 */
public class Log extends javax.swing.JFrame {

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TFusuario = new javax.swing.JTextField();
        TFclave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo-Tortelli-01-01 - copia.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 29, -1, 130));

        TFusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TFusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 195, 150, -1));

        TFclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFclaveActionPerformed(evt);
            }
        });
        getContentPane().add(TFclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 241, 150, -1));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 201, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 247, -1, -1));

        botonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-ingresar.png"))); // NOI18N
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 287, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verde-Luz-Sólido-Pintura.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFusuarioActionPerformed

    private void TFclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFclaveActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        EncriptarC objetoEcriptador = new EncriptarC();
        String usuario = TFusuario.getText().toString();
        String clave = objetoEcriptador.Encriptar(TFclave.getText().toString());
  

       EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
            
          
        EmpleadoJpaController empleadoJPA = new EmpleadoJpaController(emf);

        try{
        if(empleadoJPA.findEmpleado(Integer.parseInt(usuario)).getPin().equals(clave)){

            Empleado empleado = empleadoJPA.findEmpleado(Integer.parseInt(usuario));
            if(empleado.getCargo().equalsIgnoreCase("Gerente")){
                

                Gerente gerenteUI = new Gerente(empleado.getIdempleado(),0);
                gerenteUI.setEnabled(true);
                gerenteUI.setVisible(true);
                gerenteUI.pack();
                this.setVisible(false);

        }
            
             if(empleado.getCargo().equalsIgnoreCase("Mesero")){
                

                Mesero meseroUI = new Mesero(empleado.getIdempleado());
                meseroUI.setEnabled(true);
                meseroUI.setVisible(true);
                meseroUI.pack();
                this.setVisible(false);

        }
             
              if(empleado.getCargo().equalsIgnoreCase("Cajero")){
                

                Cajero cajeroUI = new Cajero(empleado.getIdempleado());
                cajeroUI.setEnabled(true);
                cajeroUI.setVisible(true);
                cajeroUI.pack();
                this.setVisible(false);

        }
            
        }else{
            
        JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");  
        }
       
        }catch(NumberFormatException r){
         
            JOptionPane.showMessageDialog(null, "El ID de usuario es un numero");  

        }catch(Exception e){
            
            e.printStackTrace();
        JOptionPane.showMessageDialog(null, "El empleado no existe");  

        }
       
    }//GEN-LAST:event_botonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TFclave;
    private javax.swing.JTextField TFusuario;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
