/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import JPAController.EmpleadoJpaController;
import Log.EncriptarC;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.codec.binary.Base64;
import restaurantetorteli.Empleado;


/**
 *
 * @author Alejandro
 */
public class Gerente extends javax.swing.JFrame {

    
    String imagenGlobal = "";
    
  
    /**
     * Creates new form Gerente
     */
    public Gerente() {
        initComponents();
        
          String[] items = {"Gerente", "Mesero", "Cajero"};
 
        comboCargos.setModel(new javax.swing.DefaultComboBoxModel(items));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaCrearEmpleado = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ETusuarioEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ETemailEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ETtelefonoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ETdireccionEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EThorarioEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ETclaveEmpleado = new javax.swing.JPasswordField();
        botonImagenUsuario = new javax.swing.JButton();
        imagenLabel = new javax.swing.JLabel();
        comboCargos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        botonCrearEmpleado = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("ID Usuario");

        ETusuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETusuarioEmpleadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Clave");

        ETemailEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETemailEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        jLabel5.setText("Telefono");

        ETtelefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETtelefonoEmpleadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cargo");

        jLabel7.setText("Direccion");

        ETdireccionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETdireccionEmpleadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Horario");

        EThorarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EThorarioEmpleadoActionPerformed(evt);
            }
        });

        jLabel9.setText("Foto");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonImagenUsuario.setText("Buscar");
        botonImagenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImagenUsuarioActionPerformed(evt);
            }
        });

        comboCargos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ETclaveEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ETemailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ETtelefonoEmpleado)
                            .addComponent(comboCargos, 0, 77, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EThorarioEmpleado)
                            .addComponent(ETusuarioEmpleado)
                            .addComponent(ETdireccionEmpleado)
                            .addComponent(botonImagenUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ETusuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ETclaveEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ETemailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ETtelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ETdireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EThorarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(botonImagenUsuario))
                .addGap(27, 27, 27)
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout ventanaCrearEmpleadoLayout = new javax.swing.GroupLayout(ventanaCrearEmpleado.getContentPane());
        ventanaCrearEmpleado.getContentPane().setLayout(ventanaCrearEmpleadoLayout);
        ventanaCrearEmpleadoLayout.setHorizontalGroup(
            ventanaCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ventanaCrearEmpleadoLayout.setVerticalGroup(
            ventanaCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gerente");

        botonCrearEmpleado.setText("Crear Empleado");
        botonCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(botonCrearEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(botonCrearEmpleado)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEmpleadoActionPerformed
        // TODO add your handling code here:
        
        
        ventanaCrearEmpleado.setEnabled(true);
                ventanaCrearEmpleado.setVisible(true);
                ventanaCrearEmpleado.pack();
    }//GEN-LAST:event_botonCrearEmpleadoActionPerformed

    private void ETusuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETusuarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ETusuarioEmpleadoActionPerformed

    private void ETemailEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETemailEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ETemailEmpleadoActionPerformed

    private void ETtelefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETtelefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ETtelefonoEmpleadoActionPerformed

    private void ETdireccionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETdireccionEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ETdireccionEmpleadoActionPerformed

    private void EThorarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EThorarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EThorarioEmpleadoActionPerformed

    private void botonImagenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImagenUsuarioActionPerformed
       
     JFileChooser chooser = new JFileChooser();
chooser.setCurrentDirectory(new java.io.File(".png"));
chooser.setDialogTitle("choosertitle");
chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
chooser.setAcceptAllFileFilterUsed(false);

if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
  System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
  System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
} else {
  System.out.println("No Selection ");
}
String base64 = "";
        
        try{
         java.io.File file= new java.io.File(chooser.getSelectedFile()+""); 
      java.io.FileInputStream fis= new java.io.FileInputStream(file); 
      byte[] buff= new byte[(int)file.length()]; 
      fis.read(buff); 
  // codificar base64 
       base64= new sun.misc.BASE64Encoder().encode(buff); 
      System.out.println("codificado:\n"+base64); 
      imagenGlobal = base64;
 // decodificar base64 
      byte[] bytes= new sun.misc.BASE64Decoder().decodeBuffer(base64); 
      System.out.println("decodificado:\n"+new String(bytes)); 
// TODO add your handling code here:
      
       
        byte[] btDataFile = new sun.misc.BASE64Decoder().decodeBuffer(base64);
BufferedImage image = ImageIO.read(new ByteArrayInputStream(btDataFile));
EncriptarC objeto = new EncriptarC();
objeto.getScaledImage(image,100,100);
imagenLabel.setIcon(new ImageIcon(objeto.getScaledImage(image,200,200)));


        }catch(Exception e){
            
            
        }
        
       
    }//GEN-LAST:event_botonImagenUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String cargo = "";
        int iCargo = comboCargos.getSelectedIndex();
        
        if(iCargo == 0){
            cargo = "Gerente";
        }
        
        if(iCargo == 1){
            cargo = "Mesero";
        }
        
        if(iCargo == 2){
            cargo = "Cajero";
        }
        
        
        JOptionPane.showMessageDialog(null, cargo);

        
        EncriptarC encriptador = new EncriptarC();
        
    
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
        
       EmpleadoJpaController dao = new EmpleadoJpaController(emf);//Creamos un controlador de personal
        
        Empleado empleado = new Empleado();
        
        try{
            
            
            if(dao.findEmpleado(Integer.parseInt(ETusuarioEmpleado.getText().toString())).getCargo().equalsIgnoreCase("")){
                        JOptionPane.showMessageDialog(null, "Empleado ya existe");
                        return;

        }
        }catch(Exception e){
           
        }
        
        
        try {
            
            if(imagenGlobal.equalsIgnoreCase("")){
                
                JOptionPane.showMessageDialog(null, "Seleccione una imagen");

                return;
            }
        empleado.setTipoempleado(cargo);
        empleado.setIdempleado(Integer.parseInt(ETusuarioEmpleado.getText().toString()));
        empleado.setCargo(cargo);
        empleado.setCorreo(ETemailEmpleado.getText().toString());
        empleado.setTelefono(ETtelefonoEmpleado.getText().toString());
        empleado.setDireccion(ETdireccionEmpleado.getText().toString());
        empleado.setPin(encriptador.Encriptar(ETclaveEmpleado.getText().toString()));
        empleado.setHorario(EThorarioEmpleado.getText().toString());
        empleado.setFoto(imagenGlobal);


        //JOptionPane.showMessageDialog(null, dao.findProducto(1).getNombreproducto());
        //System.out.println(dao.findProducto(1).getNombreproducto());
        
        
        
        dao.create(empleado);
            JOptionPane.showMessageDialog(null, "Empleado Creado");
        } catch (NumberFormatException ex) {
            
            //Logger.getLogger(Tortteli.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println(ex);
           JOptionPane.showMessageDialog(null, "Se espera un numero en el ID");

            ex.printStackTrace();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ya existe un empleado con este ID");

        }
        //Al ejecutar el método puede que salte una excepcion por lo que es importante lanzarla desde el main con throws Exception 
        emf.close();
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargosActionPerformed
        // TODO add your handling code here:
  
    

    }//GEN-LAST:event_comboCargosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ETclaveEmpleado;
    private javax.swing.JTextField ETdireccionEmpleado;
    private javax.swing.JTextField ETemailEmpleado;
    private javax.swing.JTextField EThorarioEmpleado;
    private javax.swing.JTextField ETtelefonoEmpleado;
    private javax.swing.JTextField ETusuarioEmpleado;
    private javax.swing.JButton botonCrearEmpleado;
    private javax.swing.JButton botonImagenUsuario;
    private javax.swing.JComboBox comboCargos;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFrame ventanaCrearEmpleado;
    // End of variables declaration//GEN-END:variables
}
