/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import JPAControl.FacturaJpaController;
import JPAControl.PagoFacturaJpaController;
import JPAControl.PagoJpaController;
import JPAControl.PedidoJpaController;
import JPAControl.ProductosFacturaJpaController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import restaurantetorteli.Factura;
import restaurantetorteli.Pago;
import restaurantetorteli.PagoFactura;
import restaurantetorteli.Pedido;
import restaurantetorteli.Producto;
import restaurantetorteli.ProductosFactura;
import restaurantetorteli.RenderTabla;

/**
 *
 * @author Alejandro
 */
public class VerFactura extends javax.swing.JFrame {

    
    
    int idFactura = 0;
     ArrayList<ProductosFactura> listaProductosSeleccion = new ArrayList<>();
     ArrayList<PagoFactura> listaPagos = new ArrayList<>();
     ArrayList<Factura> listaFacturas = new ArrayList<>();

   
    /**
     * Creates new form VerFactura
     */
    public VerFactura() {
        initComponents();
        try {
            llenarTablafacturas(tablaFacturas);
        } catch (IOException ex) {
            Logger.getLogger(VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaVerFactura = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        TFidfactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFfecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFcedula = new javax.swing.JTextField();
        TFiva = new javax.swing.JTextField();
        TFtotal = new javax.swing.JTextField();
        botonOK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        botonVerFactura = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 443, 112));

        TFidfactura.setEditable(false);
        jPanel2.add(TFidfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 83, -1));

        jLabel1.setText("ID Factura");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaPagos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 443, 118));

        jLabel2.setText("Pagos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setText("Productos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Fecha");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        TFfecha.setEditable(false);
        jPanel2.add(TFfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, -1));

        jLabel5.setText("Cedula");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel6.setText("IVA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setText("TOTAL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        TFcedula.setEditable(false);
        jPanel2.add(TFcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 76, -1));

        TFiva.setEditable(false);
        jPanel2.add(TFiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 76, -1));

        TFtotal.setEditable(false);
        jPanel2.add(TFtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 76, -1));

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });
        jPanel2.add(botonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel8.setText("Factura");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verde-Luz-Sólido-Pintura.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 570));

        javax.swing.GroupLayout ventanaVerFacturaLayout = new javax.swing.GroupLayout(ventanaVerFactura.getContentPane());
        ventanaVerFactura.getContentPane().setLayout(ventanaVerFacturaLayout);
        ventanaVerFacturaLayout.setHorizontalGroup(
            ventanaVerFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(ventanaVerFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaVerFacturaLayout.setVerticalGroup(
            ventanaVerFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(ventanaVerFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaVerFacturaLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFacturas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 80, 453, 168));

        botonVerFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-adjunta - copia 2.png"))); // NOI18N
        botonVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 266, 124, 124));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel10.setText("Ver Factura");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verde-Luz-Sólido-Pintura.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerFacturaActionPerformed

        if(tablaFacturas.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione una factura");
            return;
            
        }
        this.setVisible(false);
        
        ventanaVerFactura.setEnabled(true);
        ventanaVerFactura.setVisible(true);
        ventanaVerFactura.pack();
        
        idFactura = listaFacturas.get(tablaFacturas.getSelectedRow()).getFacturaid();
                
        TFidfactura.setText(""+idFactura);
        try {
            llenarTablaProductos(tablaProductos);
            llenarTablaPagos(tablaPagos);
            llenarDatos();
            
            
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerFacturaActionPerformed

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed

        ventanaVerFactura.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_botonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
public void llenarTablaProductos(JTable tabla) throws IOException{
    
     
            listaProductosSeleccion.clear();
    
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
            
            ProductosFacturaJpaController dao = new ProductosFacturaJpaController(emf);//Creamos un controlador de personal
           
                    
            ProductosFactura productos = new ProductosFactura();
            
            List<ProductosFactura> listaProductos = dao.findProductosFacturaEntities();
            
            
            
            for (int i = 0; i < listaProductos.size(); i++) {
                
                
                if(listaProductos.get(i).getProductosFacturaPK().getFacturaFacturaid() == idFactura){
                    
                    
                    listaProductosSeleccion.add(listaProductos.get(i));
                    
                }
        
    }
           
            
            
         
    
    
    
    
           Object listaItems[][]  = new Object[listaProductosSeleccion.size()][3];
          
          
      
          
          
           int precioAcum = 0;
          
        for (int i = 0; i < listaProductosSeleccion.size(); i++) {
            
             
            listaItems[i][0] = listaProductosSeleccion.get(i).getNombreProducto();
            listaItems[i][1] = listaProductosSeleccion.get(i).getPrecioProducto();
            listaItems[i][2] = listaProductosSeleccion.get(i).getCantidad();

            
        }
        
       
        String columna[] = new String[] {"Nombre", "Precio","Cantidad"};
        emf.close();
        
        tabla.setDefaultRenderer(Object.class,new RenderTabla());
        
        
        
        DefaultTableModel modelo = new DefaultTableModel(listaItems, columna);
        
       
        tabla.setModel(modelo);


    
}




public void llenarDatos(){
    
    
    
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
            
      FacturaJpaController dao = new FacturaJpaController(emf);//Creamos un controlador de personal
           
      Factura factura = new Factura();
      
      factura = dao.findFactura(idFactura);
          
    TFcedula.setText(Integer.toString(factura.getCedulacliente()));
    TFiva.setText(Integer.toString(factura.getIva()));
    TFtotal.setText(Integer.toString(factura.getTotalfactura()));
    TFfecha.setText(""+factura.getFechafactura().getMonth()+"/"+factura.getFechafactura().getDay());

    
    
}

public void llenarTablaPagos(JTable tabla) throws IOException{
    
     
             listaPagos.clear();
    
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
            
            PagoFacturaJpaController dao = new PagoFacturaJpaController(emf);//Creamos un controlador de personal
           
            
         
     
            
            List<PagoFactura> listaPagoFacturas = dao.findPagoFacturaEntities();
            
            
            
            for (int i = 0; i < listaPagoFacturas.size(); i++) {
                
                
                    
                    if(listaPagoFacturas.get(i).getFacturaFacturaid().getFacturaid() == idFactura){
                        
                        listaPagos.add(listaPagoFacturas.get(i));
                    }
                    
                }
        
    
           
            
            
         
    
    
    
    
           Object listaItems[][]  = new Object[listaPagos.size()][2];
          
          
      
          
          
           int precioAcum = 0;
          
        for (int i = 0; i < listaPagos.size(); i++) {
            
             
            listaItems[i][0] = listaPagos.get(i).getPagoIdPago().getNombrePago();
            listaItems[i][1] = listaPagos.get(i).getValorPago();
            
            
        }
        
       
        String columna[] = new String[] {"Tipo Pago", "Valor"};
        emf.close();
        
        tabla.setDefaultRenderer(Object.class,new RenderTabla());
        
        
        
        DefaultTableModel modelo = new DefaultTableModel(listaItems, columna);
        
       
        tabla.setModel(modelo);

    
}



public void llenarTablafacturas(JTable tabla) throws IOException{
    
     
             listaFacturas.clear();
    
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestauranteTorteliPU");//PruebaJPAPU es el nombre de nuestra unidad de persistencia
           
            FacturaJpaController factuJPA = new FacturaJpaController(emf);
            
            
           List<Factura> listaFactura = factuJPA.findFacturaEntities();

         /*  int dia = 1;
           int mes = 12;
           int año = 17;
           
           ArrayList<Factura> listaFacturasdelafecha = new ArrayList<>();
           
           
           for (int i = 0; i < listaFactura.size(); i++) {
        
               
                          if(listaFactura.get(i).getFechafactura().getDay() == dia && listaFactura.get(i).getFechafactura().getMonth()== mes && listaFactura.get(i).getFechafactura().getYear()== año){
                              
                              listaFacturasdelafecha.add(listaFactura.get(i));
                              
                          }
    }
           
           int totaldia=0;
           for (int i = 0; i < listaFacturasdelafecha.size(); i++) {
               
               totaldia = totaldia + listaFacturasdelafecha.get(i).getTotalfactura();
        
    }
           
          */ 
           
           
            
           for (int i = 0; i < listaFactura.size(); i++) {
               
               
               if(listaFactura.get(i).getEstadofactura().equalsIgnoreCase("Cancelada")){
                
                   listaFacturas.add(listaFactura.get(i));

               }
               
               
               
               
        }
           
    
    
    
    
    
           Object listaItems[][]  = new Object[listaFacturas.size()][4];
          
          
      
          
          
           int precioAcum = 0;
          
        for (int i = 0; i < listaFacturas.size(); i++) {
            
             
            listaItems[i][0] = listaFacturas.get(i).getFacturaid();
            listaItems[i][1] = listaFacturas.get(i).getFechafactura();
            listaItems[i][2] = listaFacturas.get(i).getCedulacliente();
            listaItems[i][3] = listaFacturas.get(i).getTotalfactura();
           
            
        }
        
       
        String columna[] = new String[] {"ID", "Fecha", "Cedula", "Total "};
        emf.close();
        
        tabla.setDefaultRenderer(Object.class,new RenderTabla());
        
        
        
        DefaultTableModel modelo = new DefaultTableModel(listaItems, columna);
        
       
        tabla.setModel(modelo);


    
}

    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFcedula;
    private javax.swing.JTextField TFfecha;
    private javax.swing.JTextField TFidfactura;
    private javax.swing.JTextField TFiva;
    private javax.swing.JTextField TFtotal;
    private javax.swing.JButton botonOK;
    private javax.swing.JButton botonVerFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JTable tablaPagos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JFrame ventanaVerFactura;
    // End of variables declaration//GEN-END:variables
}
